# Generated by Django 4.2.10 on 2024-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(default='NA', max_length=250),
            preserve_default=False,
        ),
    ]
