# Generated by Django 4.2.10 on 2024-03-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
